### ISSUE TITLE
Relative units

### ISSUE THREAD

**Issue by Cavalon-io** [NathanKeyzer/web-app-from-scratch-18-19#1]
Maybe it's good to use relative units as view width. This would result in the website being semi responsive without having to use media queries.

https://github.com/NathanKeyzer/web-app-from-scratch-18-19/blob/59b0d51771a55c516a0c89a41cca2cfa59ae282f/week1/public/css/styles.css#L20

**Comment by NathanKeyzer** [comment]
Changed it!
